### ISSUE TITLE
404 POST data to api

### ISSUE THREAD

**Issue by rodrigollima** [StackStorm-Exchange/stackstorm-check_mk#2]
When I execute test command: 

 source sample_event.sh
 ./stackstorm.py 

Error posting event to StackStorm: 404 Client Error: Not Found for url: https://XXX.XXX.XXX.XXX:443/api/v1/

ST2 API LOG:

2017-07-18 15:11:54,006 140512644086832 INFO logging [-] f09df310-5c8c-4c36-828b-f6a274d497cf - POST /v1/ with query={} (remote_addr='127.0.0.1',method='POST',request_id='f09df310-5c8c-4c36-828b-f6a274d497cf',query={},path='/v1/')
2017-07-18 15:11:54,007 140512644086832 INFO logging [-] f09df310-5c8c-4c36-828b-f6a274d497cf - 404 57 1.511ms
{
    "faultstring": "The resource could not be found."
} (result='{\n    "faultstring": "The resource could not be found."\n}',content_length=57,request_id='f09df310-5c8c-4c36-828b-f6a274d497cf',runtime=1.511,remote_addr='127.0.0.1',status=404,method='POST',path='/v1/')

**Comment by Mierdin** [comment]
@rodrigollima A few things:

- This is the repository for `Check_MK ` pack. You haven't posted anything specific to that yet, so just FYI, the primary stackstorm repository is https://github.com/StackStorm/st2. You'll have better results posting issues there (unless there are Check_MK details you haven't shared yet, in which case this is the right place)
- `https://XXX.XXX.XXX.XXX:443/api/v1/` isn't an API endpoint, which is why you're getting a 404. I don't know what's inside your Python script, so I have no idea how you're putting that URL together, but you need to have an endpoint in that URL. See https://api.stackstorm.com/ for our API documentation.

**Comment by LindsayHill** [comment]
@Mierdin it's this script here: https://github.com/StackStorm-Exchange/stackstorm-check_mk/blob/master/etc/stackstorm.py

Will have to look into why that's only using /api/v1/ - might be meant to have some additional customization.

**Comment by LindsayHill** [comment]
Looks like the trick is to set something like this in `/etc/check_mk/stackstorm.conf`

```
st2_api_base_url: "https://localhost/api/v1/webhooks/st2/"
```

I also found I had to explicitly cast the St2-Trace-Tag as a string, e.g.

```python
    headers = {
        'St2-Api-Key': config['api_key'],
        'St2-Trace-Tag': str(trace_tag)
    }
```

```sh
(check_mk) vagrant@bwcvagrant:/opt/stackstorm/packs/check_mk/etc$ ./stackstorm.py
/opt/stackstorm/virtualenvs/check_mk/lib/python2.7/site-packages/urllib3/util/ssl_.py:335: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/opt/stackstorm/virtualenvs/check_mk/lib/python2.7/site-packages/urllib3/util/ssl_.py:133: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/opt/stackstorm/virtualenvs/check_mk/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Sent event to StackStorm. HTTP_CODE: 202. TRACE_TAG: c3037ca1-574a-4722-9a05-2d510de103e3
(check_mk) vagrant@bwcvagrant:/opt/stackstorm/packs/check_mk/etc$ st2 trigger-instance list -n 5
+--------------------------+--------------------------------+-------------------------------+-----------+
| id                       | trigger                        | occurrence_time               | status    |
+--------------------------+--------------------------------+-------------------------------+-----------+
| 596eb387bb0f180ed863c230 | core.st2.generic.actiontrigger | Wed, 19 Jul 2017 01:19:03 UTC | processed |
| 596eb38bbb0f180ed863c231 | core.st2.generic.actiontrigger | Wed, 19 Jul 2017 01:19:07 UTC | processed |
| 596eb38bbb0f180ed863c232 | core.st2.generic.actiontrigger | Wed, 19 Jul 2017 01:19:07 UTC | processed |
| 596eba33bb0f180ed863c233 | check_mk.event_handler         | Wed, 19 Jul 2017 01:47:31 UTC | processed |
| 596eba34bb0f180ed863c238 | core.st2.generic.actiontrigger | Wed, 19 Jul 2017 01:47:32 UTC | processed |
+--------------------------+--------------------------------+-------------------------------+-----------+
(check_mk) vagrant@bwcvagrant:/opt/stackstorm/packs/check_mk$
```

**Comment by LindsayHill** [comment]
I've updated the event handler script to handle this better. Once #4 is merged, you can update to the new pack and it should work
